export { default as Home } from "./home/Home.jsx"
export { default as Card } from "./card/Card.jsx"
export { default as Admin } from "./admin/Admin.jsx"
export { default as Contact } from "./contact/Contact.jsx"
export { default as OrderHistory } from "./orderHistory/OrderHistory.jsx"
export { default as Reset } from "./auth/Reset.jsx"
export { default as Login } from "./auth/Login.jsx"
export { default as Register } from "./auth/Register.jsx"